### PR TITLE
build: update zustand from v4-rc to v4.1

### PR DESCRIPTION
**Pull request by ubinatus**
Updates the following `@web3-react` packages from zustand `v4.0.0-rc.0` to `v4.1.0`:

- `@web3-react/core`
- `@web3-react/store`
- `@web3-react/types`

It also fixes the deprecated types from `zustand`:
- `EqualityChecker`
- `State`

Mentioned packages not bumped to patch version.

### CODE REVIEW

**Comment by chybisov** [comment]
@ubinatus just curious why did you close the PR? 😄

**Comment by ubinatus** [comment]
@chybisov Hi. Because it's not a crucial PR that the new maintainers should be aware of. Also because of the inactivity on this repo. Just lowering the PRs load. Thus, `zustand` is currently on `v.4.3.x' and tbh I don't have time to update this PR, tbh. 🥲

**Comment by chybisov** [comment]
@ubinatus hi, thank you! I found it while trying to figure out why I’m getting the deprecation warnings with the latest zustand update and then discovered that this lib has outdated version of it. Yeah, because of the low activity I may consider to replace it with something else. Do you know any alternatives?

**Comment by ubinatus** [comment]
@chybisov Don't want to discourage ppl from using `web3-react` but other good alternatives I've used is `wagmi` for web3 hooks and `@rainbow-me/rainbowkit` for wallet user onboarding.

**Pull request closed without merging**
