### PR TITLE
fix: walletconnect infinite loading on success

### PR DESCRIPTION
**Pull request by defispartan**
Currently on app.uniswap.org, when a WalletConnect transaction completes, the loading state does not disappear as the "success" response is never recieved.

This PR bumps the @walletconnect/ethereum-provider dependency to include [this](https://github.com/WalletConnect/walletconnect-monorepo/pull/977) change which ensures the response is received.

### CODE REVIEW

**Review by zzmp — CHANGES_REQUESTED** [review]
There should be no changes to the yarn.lock file. Could you revert those?

Once that's reverted, this looks great, and we can merge it in. Thank you!

**Review by Mzprincess21 — APPROVED** [review]

**Review by vm — APPROVED** [review]

**Comment by vm** [comment]
Screen Shot 2022-11-10 at 7 14 13 AM

I'm actually only seeing up to 1.7.8 here? Noticed this when I tried testing on interface. @defispartan

**Comment by zzmp** [comment]
@vm this should be ^1.8.0, then, if 1.7.9 is unavailable.

**Comment by vm** [comment]
@zzmp i made a new pr, linked above

**Pull request merged**
