### PR TITLE
feat: 6 New Hooks, 7 New Connectors, Redux Integration, Upgrade Guide, Multi Account Support, Multi Blockchains, Zustand to 4.3.2, Updated/Styled Example Project, MM/CB Fixes

### PR DESCRIPTION
**Pull request by niZmosis**
I have integrated Redux with the same format as zustand. Each connector has it's own store and associated hooks. There are two new packages, core-redux and store-redux.

Updated Zustand to 4.3.2
Added ability to add and switch chain when watching an asset.
Added multi account support, via accountIndex hook.
Added how to migrate from v6 to v8 in the Readme.
Added many chains to the configuration of the example-next package as well as removed deprecated chains.
Styled example project.

**New Packages**
- core-redux
- store-redux

**New Connectors**
- BSC Wallet
- Portis Wallet
- TronLink Wallet (Tron)
- Nami Wallet (Cardano)
- Yoroi Wallet (Cardano)
- Phantom Wallet (Solana)
- Solflare Wallet (Solana)

**New Hooks**
- useAddingChain()
- useSwitchingChain()
- useWatchingAsset()
- useAccountIndex()
- useENSAvatar()
- useENSAvatars()

**MetaMask Connector**
- Fix for MM disconnecting when switching chains on certain networks
- Fix for MetaMask isActivating connector not setting on initial connection

**Coinbase Wallet Connector**
- Fix for Coinbase isActivating connector not setting when user rejects request

**Provider**
- Added hook for setting the selectedConnector. Passing no argument will reset the selectedConnector to either the defaultSelectedConnector if one was provided, or to the priorityConnector.

All features have been implemented in the example project.

### CODE REVIEW

**Review by Mzprincess21 — APPROVED** [review]

**Comment by niZmosis** [comment]
Only thing left I see is that if you change the overrideConnector after initial render, it will not update the selectedConnector. Do we want to keep the overrideConnector? If so we can put in some kind of useEffect so it causes the selectedConnector to update under the right conditions.

**Comment by niZmosis** [comment]
Almost done, I just keep getting ideas lol. Going to revamp the chain configs in the example-next.

**Comment by niZmosis** [comment]
There is an existing bug in the @web3-react/metamask package when changing chains where it may not activate after it switches chains. It is reproducible on the existing [example](https://web3-react-mu.vercel.app/), mostly when switching to the Optimism network. In the build from this PR, you will see Fuji does it every time. Coinbase Wallet is fine. Seems at one point when switching, its clearing the data like it should, but doesn't flag it as isActivating. All the changes in the PR as of now are good to go. If I find this existing MM bug, i'll add it to the PR.

**Review by Mzprincess21 — APPROVED** [review]
packages/example-next/pages/index.tsx

**Comment by niZmosis** [comment]
Maybe I didn't notice it before, but when I build then go and reload the page, I get a bunch of "Module not found: Can't resolve 'bufferutil' in '/web3-react/packages/core/node_modules/ws/lib'" for different packages like core, network and gnosis-safe.

**Comment by niZmosis** [comment]
There are a few more things I am going to do. One is providing the connector with an array of chain params on initialization, this way we don't need to pass in the params all around the app, just the chain Id. The other thing is maybe keeping error state in each connectors store. I was going to have a error state in the Web3Provider, which would work for the selected connector, but using something like useSelectedError would be a lot nicer, as if you change the selected connector from one to another while the prior still has an error, it will have the error when they go back to that connector.

**Comment by niZmosis** [comment]
I have no idea why it's failing when building on Vercel. I have cleaned the project, re bootstrapped it, ran tests, played with the example project. I have no errors on my side, and apparently don't have access to view why vercel is failing for me to fix it which is ridiculous. Probably going to revert it later and be done with it, don't even know if this PR will be accepted in the first place.

**Comment by niZmosis** [comment]
This PR is complete.

**Comment by niZmosis** [comment]
How do I get authorized to see build errors on Vercel? Pretty aggravating have it fail and not know what the problem is.

**Comment by Benjythebee** [comment]
You got this man, I can't wait for this

**Comment by niZmosis** [comment]
Everything is good besides the images not loading, I'll keep messing with it.

**Comment by niZmosis** [comment]
I put a lot of work into this, with no breaking changes. I have merged into the main quite a few times, and I feel like this PR is invisible. What's wrong with this build where it's not getting any attention from the maintainers? Where do you guys even see this project going? What are the future plans? All the things I have added are in the example, and you wouldn't know it but metamask and cb wallets are on redux while the others are on zustand to show the flexibility and if someone has redux in their project already they won't need to install zustand just to use this package. I've updated packages, made code more similar between connectors. Broke out code to make it cleaner. There is so much that can be done with this feature wise. The team should make a list of their roadmap for this package, it's been in beta for over a year. Why no detailed readme? Yes it's in beta and you'd probably have to go and redo the whole readme, but that's what needs to happen, it's part of progress. From here either my PR dies or if going to be accepted, I will add even more to the readme. Yes this is a big ass merge, but it can't be broken up, the are subtle changes that need to be in place for all this to work with the different connectors. I go through the issues and see what people need. For instance, some people when they activate a connector, they need the address or chain to do additional things in the same block of code and not wait for a rerender with a useeffect just to make an api call. That's why activate and connect eagerly return the stores state. Anyways enough with my rant, it's just that I put a lot of thought and effort into this. You guys gangbanged the shit out of the last PR so I know there are quite a few of you. Someone review this thing.

**Comment by grabbou** [comment]
Hey!

Unfortunately, we discussed this PR and decided not to merge it going forward. I understand this is not the outcome that you expected, but we - as a team - had no visibility into your work and were not expecting such a PR to arrive. While I really appreciate your time spent on our project, we simply can't merge it for that reason alone.

To put more context into it, we don't have any items on the roadmap rather than maintaining the current state of web3-react by providing necessary fixes and small features that are primarily required by Uniswap. We are happy with the project's current state, and while I certainly see hooks such as `useENSAvatar()` a useful addition, they're out of scope for what we consider priorities right now.

Once again, I am really sorry to be closing such impressive PR. If you decide to contribute to our project again, you're more than welcome, and feel free to engage with me into discussions here on Github so that we can plan feature developments out and make sure that as soon as they're completed, they're merged right away.

**Pull request closed without merging**
