### PR TITLE
Identify Connectors

### PR DESCRIPTION
**Pull request by pedrouid**
This PR adds an id to each connector to make it possible to identify them for UI development

As mentioned on issue #184, we want to make web3-react compatible with Web3Modal 2.0. Currently it's impossible to use the two together with v1.0 but if we simply add an id to each connector, our UI can detect and display the connectors properly for user to select.

It's a small and backwards-compatible change which will make Web3Modal 2.0 immediately compatible with all the connectors on web3-react

### CODE REVIEW

**Comment by pedrouid** [comment]
Hey @NoahZinsmeister, can you include this one the next release? It would really help us ship Web3Modal v2.0 earlier and make web3-react connectors compatible

**Comment by esemeniuc** [comment]
Second this, would love to see this!

**Comment by pedrouid** [comment]
Hey @NoahZinsmeister 👋  I just merged the latest changes from v6 and fixed CI. Could we get this included in the next release?

**Comment by AlexBHarley** [comment]
@NoahZinsmeister any timeline for this getting in? Would be really great for the ecosystem. WalletConnect V2 adoption will really skyrocket once the various frontend libraries support it.

**Review by ssijak — APPROVED** [review]

**Comment by NoahZinsmeister** [comment]
hey @pedrouid, sorry for the really slow response here. going forward, i'm going to focus dev efforts on v8 release, currently in `beta` in the `main` branch. do you still need string ids on connectors?

also, the walletconnect connector in that branch is still on v1, but looking forward to adding a v2 version! tracking here: https://github.com/NoahZinsmeister/web3-react/issues/348

**Review by faves4less — APPROVED** [review]

**Pull request closed without merging**
