### PR TITLE
🔗 TallyHo! connector

### PR DESCRIPTION
**Pull request by greg-nagy**
# What? 

This PR implements a connector for Tally Ho!. The connector supports eager connect (both from useEffects and through constructor parameter) and lazy connect.

# How? 

Creates a package that implements the connector and adds to the example app.

# Test

* install and set up Tally Ho!
  * [install Tally Ho!](https://chrome.google.com/webstore/detail/tally-ho/eajafomhmkipbjmfmhebemolkcicgfmd)
  * import a seed phrase
* example 
  * use this link: https://web3-react-git-fork-tallycash-tally-ho-integration-noahwz.vercel.app/
  * or start the example locally
    * yarn bootstrap
    * yarn start
    * open http://localhost:3000/

# Demo
CleanShot 2022-03-28 at 11 56 33

### CODE REVIEW

**Comment by greg-nagy** [comment]
I have officially 0 idea why vercel bot fails :( 
Everything works locally.

**Comment by NoahZinsmeister** [comment]
hey @greg-nagy , sorry you've been having trouble. the vercel logs contain the following error:

```
Failed to compile.
--
13:23:49.699 |  
13:23:49.699 | ./connectors/tally-ho.ts:4:53
13:23:49.699 | Type error: Type 'TallyHo' does not satisfy the constraint 'Connector'.
13:23:49.699 | Property 'customProvider' is missing in type 'TallyHo' but required in type 'Connector'.
13:23:49.699 |  
13:23:49.699 | 2 \| import { TallyHo } from '@web3-react/tally-ho'
13:23:49.700 | 3 \|
13:23:49.700 | > 4 \| export const [tallyHo, hooks] = initializeConnector<TallyHo>((actions) => new TallyHo(actions, false))
```

i suspect this is either because your PR isn't up-to-date with HEAD, or the version of some `@web3-react/*` package in your `package.json` doesn't match the actual version of the sibling package, or both

**Comment by greg-nagy** [comment]
hey @NoahZinsmeister 

Thank you for the feedback, and sorry for taking this long with this PR to fix. 
Rebased the PR to the current head and doubled checked everything. It's working now. 

Let me know if you would like anything to be changed. Had to massage the eager connection a bit, 
and I suspect this is an issue for other wallets as well eg. MetaMask. 

The issue is that if connectEagerly is set to `true` when instantiating the provider then the window is `undefined` which 
is used as a signal that we are in SSR context. But in reality, it's just too soon in the initialization process and if we wait a bit we will have a window object. 

The other thing I noticed is if connectEagerly is set to true at initialization time and also used in a hook then 2 initialization process is started. Shouldn't cause any issue, but good to have it in mind.

**Comment by wojciech-turek** [comment]
Hi @NoahZinsmeister whenever you have a moment it'd be amazing if you could have a look here.

**Comment by mhluongo** [comment]
Conflicts here @greg-nagy

**Comment by grabbou** [comment]
Hey! Unfortunately, we're not accepting external connectors to the core at this time. Consider releasing this package as a separate individual npm package.

**Pull request closed without merging**
